name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Trigger deployment on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2   # Checkout code so the workflow can access it

      # Step 2: Install Vercel CLI (for deployment)
      - name: Set up Vercel CLI
        run: |
          npm install -g vercel  # Install the Vercel CLI to interact with Vercel

      # Step 3: Authenticate with Vercel using GitHub Secrets
      - name: Authenticate with Vercel
        run: vercel login ${{ secrets.VERCEL_TOKEN }}   # Authenticate using the Vercel token (GitHub Secret)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Vercel token to authenticate with Vercel

      # Step 4: Deploy to Vercel
      - name: Deploy to Vercel
        run: vercel --prod --confirm  # Deploys to Vercel automatically
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}    # Pass the Supabase URL securely
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}    # Pass the Supabase key securely
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}  # Pass the Telegram Bot token securely
